FROM rabbitmq:4-management

ADD --chmod=644 https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/releases/download/v4.2.0/rabbitmq_delayed_message_exchange-4.2.0.ez \
    $RABBITMQ_HOME/plugins/rabbitmq_delayed_message_exchange-4.2.0.ez

RUN rabbitmq-plugins enable --offline rabbitmq_stream rabbitmq_stream_management rabbitmq_delayed_message_exchange
